
DATA_SEPARATOR          = ';'

LOGIN_PREFIX            = 'L'
REGISTER_PREFIX         = 'R'
LOGOUT_PREFIX           = 'LO'
CLOSING_APP_PREFIX      = 'LC'

CALENDAR_INSERT_PREFIX       = 'CI'
CALENDAR_MODIFY_PREFIX       = 'CM'
CALENDAR_DELETE_PREFIX       = 'CD'

CALENDAR_INSERT_USER_PREFIX  = 'CIU'
CALENDAR_DELETE_USER_PREFIX  = 'CDU'

CALENDAR_GET_NAMES_PREFIX    = 'CGN'
CALENDAR_GET_INFO_PREFIX     = 'CGI'
CALENDAR_GET_EVENTS_PREFIX   = 'CGE'
CALENDAR_GET_USERS_PREFIX    = 'CGU'

EVENT_INSERT_PREFIX     = 'EI'
EVENT_MODIFY_PREFIX     = 'EM'
EVENT_DELETE_PREFIX     = 'ED'

MAX_DATA_LENGTH = 1024
TIMEOUT_VALUE   = 2000
ERROR_VALUE   = '1'
TIMEOUT_VALUE = '2'
DATA_END = '\n'

DATE_FORMAT = 'dd.MM.yyyy'

SCREEN_MODELS_FOLDER  = 'screenModels'
MAIN_APP_WINDOW       = 'mainWindow.ui'

SCREEN_LOGIN_REGISTER = 'loginWindow.ui'

SCREEN_CALENDAR_LIST  = 'calendarList.ui'
SCREEN_NEW_CALENDAR   = 'addNewCalendar.ui'
SCREEN_CALENDAR_VIEW  = 'calendar.ui'

