
DATA_SEPARATOR          = ';'

LOGIN_PREFIX            = 'L'
REGISTER_PREFIX         = 'R'
LOGOUT_PREFIX           = 'LO'
CLOSING_APP_PREFIX      = 'LC'

CALENDAR_INSERT_PREFIX       = 'CI'
CALENDAR_INSERT_USER_PREFIX  = 'CIU'
CALENDAR_MODIFY_PREFIX       = 'CM'
CALENDAR_DELETE_PREFIX       = 'CD'
CALENDAR_DELETE_USER_PREFIX  = 'CDU'
CALENDAR_GET_NAMES           = 'CGN'
CALENDAR_GET_CALENDAR_INFO   = 'CGI'
CALENDAR_GET_EVENTS_PREFIX   = 'CGE'

EVENT_INSERT_PREFIX     = 'EI'
EVENT_MODIFY_PREFIX     = 'EM'
EVENT_DELETE_PREFIX     = 'ED'

MAX_DATA_LENGTH = 1024
ERROR_VALUE = '1'

APPLICATION_PORT = 1234
APPLICATION_HOST = 'localhost'

SCREEN_MODELS_FOLDER  = 'screenModels'
MAIN_APP_WINDOW       = 'mainWindow.ui'

SCREEN_LOGIN_REGISTER = 'loginWindow.ui'

SCREEN_CALENDAR_LIST  = 'calendarList.ui'
SCREEN_NEW_CALENDAR   = 'addNewCalendar.ui'
SCREEN_CALENDAR_VIEW  = 'calendar.ui'

